stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: connectedgames/mcmirror:latest
      pushRemote: true
      registry: index.docker.io

  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: mcmirror-phppm:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
