stages:
- name: Build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: connectedgames/mcmirror:latest
      pushRemote: true
      registry: 127.0.0.1:34361
timeout: 60
