apiVersion: apps/v1
kind: Deployment
metadata:
  name: phppm
  namespace: mcmirror
  labels:
    app: mcmirror-phppm
spec:
  template:
    metadata:
      labels:
        app: mcmirror-phppm
    spec:
      containers:
      - image: mcmirror-phppm:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: phppm
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /var/www/
          name: mcmirror-builds
          readOnly: true
        - mountPath: /workspace/.env
          name: mcmirror-config
          readOnly: true
          subPath: .env
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mcmirror-builds
        persistentVolumeClaim:
          claimName: mcmirror-builds
      - configMap:
          defaultMode: 272
          name: mcmirror-config
          optional: false
        name: mcmirror-config
  selector:
    matchLabels:
      app: mcmirror-phppm