kind: Service
apiVersion: v1
metadata:
  name: phppm-service
  namespace: mcmirror
spec:
  selector:
    app: mcmirror-phppm
  clusterIP: None
  ports:
    - name: default
      port: 42
      protocol: TCP
      targetPort: 42
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phppm
  namespace: mcmirror
  labels:
    app: mcmirror-phppm
spec:
  template:
    metadata:
      labels:
        app: mcmirror-phppm
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        name: phppm
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /var/www/
          name: mcmirror-builds
          readOnly: true
        - mountPath: /workspace/.env
          name: mcmirror-config
          readOnly: true
          subPath: .env
      restartPolicy: Always
      volumes:
      - name: mcmirror-builds
        persistentVolumeClaim:
          claimName: mcmirror-builds
      - configMap:
          defaultMode: 272
          name: mcmirror-config
          optional: false
        name: mcmirror-config
  selector:
    matchLabels:
      app: mcmirror-phppm